extends:
  - "eslint:recommended"
  - "prettier"
  - "airbnb-base"
rules:
  arrow-body-style: "off"
  comma-dangle:
    - "error"
    - "always-multiline"
  curly:
    - "error"
    - "all"
  func-names:
    - "error"
    - "as-needed"
  import/no-dynamic-require: "off"
  import/no-extraneous-dependencies: "off"
  import/prefer-default-export: "off"
  indent: "off"
  linebreak-style: "off"
  max-len:
    - "warn"
    - "120"
    - "ignoreComments": true
    - "ignoreTrailingComments": true
  no-console: "off"
  no-else-return: "off"
  no-lonely-if: "off"
  no-trailing-spaces:
    - "error"
    - "ignoreComments": true
  no-unused-vars:
    - "error"
    - "argsIgnorePattern": _
    - "varsIgnorePattern": _
  prefer-template: "off"
  quotes:
    - "error"
    - "double"
    - "avoidEscape": true
  spaced-comment:
    - "error"
    - "always"
    - "exceptions":
        - "*"
  strict: "off"
